"""Pull request creation -- how agent work reaches a human, and how it ships.

The single most important product decision in the gateway is encoded here: **the
agent opens a pull request; it never merges one.** `git_merge_pull_request` is on
the never-expose list and is not implemented.

The pull request is also the *only* deployment path. The agent writes Databricks
Asset Bundle files -- `resources/<job>.yml` and `source/<pipeline>.py` -- into
the customer's bundle repository. From there their existing pipeline takes over:
CI runs the tests, `bundle validate` produces the plan, a tech lead approves, and
their CD runs `bundle deploy`. We generate; they ship.

That is a better security posture than owning a deploy tool and gating it, and
it is a far shorter conversation with their platform team: an agent-authored
pull request is handled exactly like a human-authored one.

That is not only a safety property. It is the adoption property. Data engineers
already know how to review a diff, and a PR puts agent output into the review
workflow they already trust, rather than asking them to trust a chat approval.
It is also what makes ADR-0003's `human_edit_lines` measurable at all: the diff
between what the agent proposed and what was merged *is* the metric.
"""

from __future__ import annotations

import base64
from typing import Any

import httpx
import structlog

from mcp_gateway import scopes
from mcp_gateway.tools.base import Tool, ToolContext, ToolError

log = structlog.get_logger(__name__)

_TIMEOUT = httpx.Timeout(30.0, connect=10.0)


def _normalise_path(path: str) -> str:
    """Azure DevOps wants repository paths rooted at `/`."""
    return path if path.startswith("/") else f"/{path}"


def _raise_for_azdo(response: httpx.Response, action: str) -> None:
    """Turn an Azure DevOps error into something an agent can act on.

    The message reaches the model, so it says what to do rather than echoing a
    status code, and it never includes the token or the response body -- an Azure
    DevOps error page can contain organisation detail we have no reason to hand
    to a language model.
    """
    if response.is_success:
        return

    if response.status_code in (401, 403):
        raise ToolError(
            f"the agent principal is not permitted to {action} in this repository. "
            f"It needs Contribute and Create pull request, and must not have any "
            f"Bypass policies permission.",
            error_class="azdo_forbidden",
            retryable=False,
        )
    if response.status_code == 404:
        raise ToolError(
            f"could not {action}: repository or project not found",
            error_class="azdo_not_found",
            retryable=False,
        )
    if response.status_code >= 500:
        raise ToolError(
            f"Azure DevOps returned a server error while trying to {action}",
            error_class="azdo_server_error",
            retryable=True,
        )
    raise ToolError(
        f"Azure DevOps rejected the request to {action} ({response.status_code})",
        error_class="azdo_rejected",
        retryable=False,
    )


def _agent_pr_body(
    ctx: ToolContext, rationale: str, bundle_summary: str | None = None
) -> str:
    """PR description.

    Provenance goes in the body, not just in a label, because it is the first thing
    a reviewer sees and the thing an auditor asks for six months later.
    """
    plan = ""
    if bundle_summary:
        # What the change actually produces in the target workspace. A reviewer
        # reads this before the diff -- the diff says what moved, this says what
        # it will do.
        plan = "\n**Bundle plan** (`bundle validate`):\n\n" + bundle_summary + "\n"

    return f"""{rationale}
{plan}

---
**Generated by an AI DevOps Platform agent.**

| | |
|---|---|
| Agent | `{ctx.principal.agent.agent_type}` |
| Agent principal | `{ctx.principal.agent.name}` |
| Requested by | `{ctx.principal.invoked_by}` |
| Run | `{ctx.run_id}` |
| Environment | `{ctx.environment}` |

This pull request was opened by an automated agent and has not been merged by one.
It deploys through your existing pipeline, not through the platform -- review,
approve and merge it exactly as you would a human's. Trace and full reasoning for
this run are available in your own Azure subscription.
"""


async def git_open_pull_request(
    ctx: ToolContext,
    *,
    repository: str,
    branch: str,
    base: str,
    title: str,
    rationale: str,
    files: list[dict[str, str]],
    bundle_summary: str | None = None,
) -> dict[str, Any]:
    """Create a branch, commit files to it, and open a pull request.

    `files` is a list of {"path": ..., "content": ...}. File count is capped by
    policy -- a 200-file agent PR is not reviewable, and an unreviewable PR defeats
    the point of the tool.
    """
    log.info(
        "git_open_pull_request",
        run_id=ctx.run_id,
        agent_principal=ctx.principal.agent.name,
        repository=repository,
        branch=branch,
        base=base,
        file_count=len(files),
    )

    if not files:
        raise ToolError(
            "a pull request with no file changes is not useful",
            error_class="git_empty_changeset",
            retryable=False,
        )

    org, project = ctx.azure_devops_org, ctx.azure_devops_project
    if not org or not project:
        raise ToolError(
            "Azure DevOps organisation and project are not configured for this "
            "tenant; set ADP_AZDO_ORG and ADP_AZDO_PROJECT",
            error_class="azdo_not_configured",
            retryable=False,
        )

    # A separate, narrowly scoped token. The agent needs Contribute and Create
    # pull request on this repository and nothing else -- crucially not any of
    # the "Bypass policies" permissions, which would let it route around the
    # branch policy that makes a human reviewer mandatory.
    token = ctx.get_token(scopes.AZURE_DEVOPS)
    api = f"https://dev.azure.com/{org}/{project}/_apis/git/repositories/{repository}"
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    params = {"api-version": "7.1"}

    async with httpx.AsyncClient(timeout=_TIMEOUT) as client:
        # 1 -- resolve the base commit -------------------------------------
        try:
            refs = await client.get(
                f"{api}/refs",
                headers=headers,
                params={**params, "filter": f"heads/{base}"},
            )
        except httpx.HTTPError as exc:
            raise ToolError(
                "could not reach Azure DevOps",
                error_class="azdo_unreachable",
                retryable=True,
            ) from exc

        _raise_for_azdo(refs, "resolve base branch")

        values = refs.json().get("value") or []
        if not values:
            raise ToolError(
                f"base branch {base!r} does not exist in {repository!r}",
                error_class="azdo_base_not_found",
                retryable=False,
            )
        base_commit = values[0]["objectId"]

        # 2 -- create the branch with one commit ---------------------------
        #
        # `oldObjectId` is the base commit, not all-zeros. Azure DevOps treats
        # all-zeros as "create an orphan ref", which produces a branch with no
        # parent -- the pull request would then show every file in the repository
        # as deleted alongside ours. Pointing it at the base commit is what makes
        # this a branch *from* main rather than a parallel history.
        push_payload = {
            "refUpdates": [
                {"name": f"refs/heads/{branch}", "oldObjectId": base_commit}
            ],
            "commits": [
                {
                    "comment": f"{title}\n\nAgent run {ctx.run_id}",
                    "changes": [
                        {
                            "changeType": "add",
                            "item": {"path": _normalise_path(f["path"])},
                            "newContent": {
                                "content": base64.b64encode(
                                    f["content"].encode("utf-8")
                                ).decode("ascii"),
                                "contentType": "base64encoded",
                            },
                        }
                        for f in files
                    ],
                }
            ],
        }

        push = await client.post(f"{api}/pushes", headers=headers, params=params,
                                 json=push_payload)

        if push.status_code == 409:
            # The branch already exists. Non-retryable: retrying pushes the same
            # content again, and silently reusing someone else's branch is worse
            # than failing.
            raise ToolError(
                f"branch {branch!r} already exists; pick a unique branch name",
                error_class="azdo_branch_exists",
                retryable=False,
            )
        _raise_for_azdo(push, "create branch")

        # 3 -- open the pull request ---------------------------------------
        pr_payload = {
            "sourceRefName": f"refs/heads/{branch}",
            "targetRefName": f"refs/heads/{base}",
            "title": title,
            "description": _agent_pr_body(ctx, rationale, bundle_summary),
            "labels": [{"name": "agent-generated"}],
        }

        pr = await client.post(f"{api}/pullrequests", headers=headers, params=params,
                               json=pr_payload)
        _raise_for_azdo(pr, "open pull request")

    body = pr.json()
    pr_id = body.get("pullRequestId")
    web_url = (
        f"https://dev.azure.com/{org}/{project}/_git/{repository}/pullrequest/{pr_id}"
    )

    log.info(
        "git_pull_request_opened",
        run_id=ctx.run_id,
        pull_request_id=pr_id,
        branch=branch,
        base=base,
        base_commit=base_commit,
    )

    return {
        "pull_request_id": pr_id,
        "url": web_url,
        "branch": branch,
        "base": base,
        "base_commit": base_commit,
        "file_count": len(files),
        "opened_by": ctx.principal.agent.name,
        # Deliberate: the agent is told, in its own tool result, that it is done.
        # Nothing it can call next will merge this.
        "next_step": "awaiting human review; the agent cannot merge this",
    }


GIT_OPEN_PULL_REQUEST = Tool(
    name="git_open_pull_request",
    description=(
        "Open a pull request containing generated Databricks Asset Bundle files. "
        "This is how work ships: put job definitions in resources/<name>.yml and "
        "code in source/<name>.py, validate the bundle first, then open the PR "
        "into the customer's bundle repository. Their CI/CD deploys it. The agent "
        "cannot merge the pull request and cannot write to a protected branch. "
        "Include a clear rationale and the bundle summary -- together they are "
        "what a reviewer reads first."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "repository": {"type": "string"},
            "branch": {
                "type": "string",
                "description": "Source branch to create. Must start with the prefix "
                "permitted by policy, e.g. 'agent/'.",
            },
            "base": {"type": "string", "description": "Branch to merge into"},
            "title": {"type": "string"},
            "rationale": {
                "type": "string",
                "description": "Why these changes, in prose. Becomes the PR body.",
            },
            "bundle_summary": {
                "type": "string",
                "description": "Output of databricks_bundle_summary, so the "
                "reviewer sees the effect of the change and not only its diff.",
            },
            "files": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "path": {"type": "string"},
                        "content": {"type": "string"},
                    },
                    "required": ["path", "content"],
                },
            },
        },
        "required": ["repository", "branch", "base", "title", "rationale", "files"],
    },
    handler=git_open_pull_request,
    mutating=True,
)
